<?binding.jca DrugDatabase_db.jca?>
<wsdl:definitions name="DrugDatabase" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Saude365/HSN/DrugDatabase" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Saude365/HSN/DrugDatabase" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DrugDatabase">
    <plt:partnerLinkType name="DrugDatabase_plt">
        <plt:role name="DrugDatabase_role">
            <plt:portType name="tns:DrugDatabase_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DrugDatabase" schemaLocation="xsd/DrugDatabase_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DrugsCollection_msg">
        <wsdl:part name="DrugsCollection" element="top:DrugsCollection"/>
    </wsdl:message>
    <wsdl:portType name="DrugDatabase_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:DrugsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
