<?binding.jca MergeScreening_db.jca?>
<wsdl:definitions name="MergeScreening" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Saude365/HSN/MergeScreening" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Saude365/HSN/MergeScreening" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeScreening">
    <plt:partnerLinkType name="MergeScreening_plt">
        <plt:role name="MergeScreening_role">
            <plt:portType name="tns:MergeScreening_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MergeScreening" schemaLocation="xsd/MergeScreening_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ScreeningCollection_msg">
        <wsdl:part name="ScreeningCollection" element="top:ScreeningCollection"/>
    </wsdl:message>
    <wsdl:portType name="MergeScreening_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:ScreeningCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
